//Cadastro usuário
POST http://localhost:3003/users
Content-Type: application/json

{
  "name": "Rodrigo",
  "email": "rodrigo@email.com",
  "password": "123456789"
}

###

//Busca por todos os usuários
GET http://localhost:3003/users
Content-Type: application/json

###

//Cadastro de produto
POST http://localhost:3003/products
Content-Type: application/json

{
  "name": "Celular",
  "price": 1500,
  "imageUrl": "https://i.picsum.photos/id/160/3200/2119.jpg?hmac=cz68HnnDt3XttIwIFu5ymcvkCp-YbkEBAM-Zgq-4DHE"
}

###

//Busca por todos os produtos
GET http://localhost:3003/products
Content-Type: application/json


###

//Registro de compra
POST http://localhost:3003/purchases
Content-Type: application/json

{
  "userId": "106",
  "productId": "138",
  "quantity": 9
}

###

//Busca das compras de um usuário
GET http://localhost:3003/users/106/purchases
Content-Type: application/json